"""Données du générateur d'acronymes.

- ``GROS_MOTS`` : liste des gros mots français servant d'acronymes.
"""

GROS_MOTS = (
    # Jurons / interjections (du plus fort au plus doux)
    "MERDE",
    "PUTAIN",
    "BORDEL",
    "FOUTRE",
    "CHIER",
    "ZUT",
    "FLUTE",
    "MINCE",
    "PUNAISE",
    "CREVINDIEU",
    "SAPRISTI",
    "SACREBLEU",
    "MORBLEU",
    "PARBLEU",
    "FICHTRE",
    "DIANTRE",
    "BIGRE",

    # Insultes générales (personne)
    "CON",
    "CONNARD",
    "CONNASSE",
    "CRETIN",
    "ABRUTI",
    "DEBILE",
    "IMBECILE",
    "IDIOT",
    "COUILLON",
    "ANDOUILLE",
    "CRUCHE",
    "BUSE",
    "NIAIS",
    "BOULET",
    "TOCARD",
    "GLAND",
    "BLAIREAU",
    "BOUFFON",
    "GUIGNOL",
    "BOLOSS",

    # Registre méprisant / moral
    "SALAUD",
    "SALOPE",
    "ORDURE",
    "FUMIER",
    "CRAPULE",
    "VAURIEN",
    "GREDIN",
    "FRIPOUILLE",
    "CANAILLE",
    "CHAROGNE",
    "ENFOIRE",
    "ENFLURE",
    "POURRITURE",
    "BATARD",
    "GOUJAT",
    "MUFLE",
    "RUSTRE",
    "BUTOR",

    # Qualificatifs dévalorisants
    "NUL",
    "NAZE",
    "MINABLE",
    "MINUS",
    "FOIREUX",
    "RIPOU",
    "POURRI",
    "RELOU",
    "CHIANT",
    "EMMERDANT",

    # Crudités anatomiques / sexuelles
    "CUL",
    "BITE",
    "ZOB",
    "COUILLE",
    "CHATTE",
    "NICHON",
    "PUTE",
    "PETASSE",
    "GARCE",
    "POUFIASSE",
    "TRAINEE",
    "CATIN",
    "GRUE",
    "COCU",
    "BRANLEUR",
    "EMMERDEUR",
    "CHIEUR",

    # Scatologique
    "BOUSE",
    "CACA",
    "PISSE",
    "PROUT",
    "PIPEAU",
)
